### ISSUE TITLE
Some < signs in template gets escaped in html entity &lt;

### ISSUE THREAD

**Issue by aurelije** [schneidexe/tpl#10]
Having template like this:
`{
  "checks": {
    "{{ .APPLICATION }}_file_executions": {
      "test": "'< >'<?<,,   < ? > ",
      "test2" "<br> < > "
      "cron": "{{ .TRACKING_BATCH_CRON }}",
      "handlers": [
        "mailer",
        "hipchat"
      ],
    }
  }
}
`
and running tpl command I can see that all < characters except those that are part of html tags gets escaped to html entity &lt; Previously it was not like that but now that tpl uses html templates it produced this bug. Workaround is to just switch the expression so instead of < character expression will use >.

**Comment by schneidexe** [comment]
fixed with 7ecec03bb935c1bb400648c604b8de7a0379014a (going back to text/template)
