### ISSUE TITLE
tpl 0.4.6 fails to parse string with \

### ISSUE THREAD

**Issue by cgarciaarano** [schneidexe/tpl#13]
tpl v0.4.6 complains about syntax when parsing variable values with some combinations of `\`.

For example the following template file (and variants with single quotes, no quotes, etc):
```
{{ $api_pattern := "/.*\/api\/.*/" -}}
```

fails with 

```
panic: template: kk.tpl:1: invalid syntax

goroutine 1 [running]:
text/template.Must(...)
	/opt/local/lib/go/src/text/template/helper.go:23
main.main()
	/Users/thomassc/work/go/src/github.com/schneidexe/tpl/tpl.go:116 +0x8db
```

Other examples:
- `\.` fails
- `\d` fails
- `\a` works

Escaping backslash generates the expected string, so it seems it's escaping the string as well. Maybe a warning in README will be enough.

**Comment by schneidexe** [comment]
Hey @cgarciaarano, as I had subscriptions disabled I missed that one. Will have a look soon! :)

**Comment by schneidexe** [comment]
Seem you have to use `\\` to escape them. If you set the backslash in a shell env it works, setting vars inside the template is not an issue of tpl but rather golang template. But if you use double-\ your expression above renders fine... For shell env I added a test...
