### ISSUE TITLE
numbers get converted to floating point instead of staying untouched

### ISSUE THREAD

**Issue by sk3l3t0r** [schneidexe/tpl#3]
When a placeholder's value is a number the placeholder is replaced by weird floating-point representation of that same number instead of being unchanged / treated as a string.

exmaple:
1) export TOKEN=59614658972
2) tpl file contains {{ .TOKEN }}
3) after processing with tpl -t the {{ .TOKEN }} gets replaced with 5.9614658972e+10

**Comment by schneidexe** [comment]
So looks like a plain number (amongst other primitives) is valid JSON (see http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf). ```tpl``` parses this number with ```json.Unmarshal()```. The result is a golang ```float64``` which gets printed in scientific format upon a certain length.
