### ISSUE TITLE
Special character encoding issue inside Docker

### ISSUE THREAD

**Issue by jcustovic** [schneidexe/tpl#6]
Hi,

while running in docker I am facing UTF-8 encoding issues. Special character e.g. €ćčžäö are getting printet to ? character.

Example template: Can you give me {{ .money }}? 
env money is equal to 500€
Output is Can you give me 500?? 

When I tried outside of docker I got no problem and everything works as expected.

What could be the issue?

BR.
Jan

**Comment by schneidexe** [comment]
@jcustovic you need to set the env variable ```LANG``` to ```C.UTF-8```, either using ```ENV LANG C.UTF-8``` in your ```Dockerfile``` or starting your container with ```-e LANG=C.UTF-8```. Does this help?

Source: https://stackoverflow.com/questions/25637292/cannot-type-unicode-in-a-ubuntu14-04-container-can-type-just-fine-in-busybox

**Comment by schneidexe** [comment]
@jcustovic you need to set theenv variable LANG to C.UTF-8, either using ```ENV LANG C.UTF-8``` in your ```Dockerfile``` or starting your container with ```-e LANG=C.UTF-8```. Does this help?

**Comment by jcustovic** [comment]
Hi @schneidexe,

yes I have tried with `ENV LANG en_US.UTF-8` and now with` ENV LANG C.UTF-8` but it does not help. Also it appears that this env is even not set because command `locale `gives POSIX. I have also tried to set POSIX on VM and still the tpl works well... Also `echo `with UTF-8 chars works normally.  Do you have any other ideas?

**Comment by schneidexe** [comment]
As discussed this is probably not a ```tpl``` bug, as is also happens with ```echo``` in your case. Let's wait for IM-668...

**Comment by schneidexe** [comment]
So looks like this was a groovy/jenkins issue. Adding ```-Dfile.encoding=UTF-8``` to slave JVM args helped (see https://issues.jenkins-ci.org/browse/JENKINS-31096).
