### ISSUE TITLE
Range shouldn't try to iterate over empty variable

### ISSUE THREAD

**Issue by rotilho** [schneidexe/tpl#7]
I have the following code which is failing when I have a empty env variable

{{ range .REDIS_SAVE }}
save {{ .seconds }} {{ .changes }}
{{ end }}

If I add a empty check it works fine

{{ if .REDIS_SAVE }}
{{ range .REDIS_SAVE }}
save {{ .seconds }} {{ .changes }}
{{ end }}
{{ end }}

**Comment by schneidexe** [comment]
I switched from ```text/template``` to ```html/template``` which seems to handle this better...
